name: "Release Binary"

# Pairs with .goreleaser.yaml file for configuration.

on:
  workflow_dispatch:
  push:
    tags:
      - "v[0-9]+\\.[0-9]+\\.[0-9]+"
      - "v[0-9]+\\.[0-9]+\\.[0-9]+-rc[0-9]+"

# Test Locally with:
# goreleaser build --skip validate --snapshot --clean

jobs:
  release-binary:
    env:
      VERSION: v0.0.1
      COSMWASM_VERSION: v2.2.3
      TM_VERSION: v0.38.17
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.8'

      - name: Clean up dist directory
        run: rm -rf dist

      - name: Build
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: build --skip-validate

      # - name: Release
      #   uses: goreleaser/goreleaser-action@v5
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     version: latest
      #     args: release --skip-validate --clean
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}