name: "Release Binary"

# Pairs with .goreleaser.yaml file for configuration.

on:
  workflow_dispatch:
  push:
    tags:
      - "v[0-9]+\\.[0-9]+\\.[0-9]+"
      - "v[0-9]+\\.[0-9]+\\.[0-9]+-rc[0-9]+"

# Test Locally with:
# goreleaser build --skip validate --snapshot --clean

jobs:
  release-binary:
    env:
      VERSION: v0.0.1
      COSMWASM_VERSION: v2.2.3
      TM_VERSION: v0.38.17
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.8'

      - name: Clean up dist directory
        run: rm -rf dist

      - name: Check docker
        run: |
          docker --version

      - name: Release with goreleaser container
        run: |
          docker run \
          --rm \
          -e CGO_ENABLED=1 \
          -e GITHUB_TOKEN=$(GITHUB_TOKEN) \
          -e TM_VERSION=$(TM_VERSION) \
          -e COSMWASM_VERSION=$(COSMWASM_VERSION) \
          -v `pwd`:/go/src/enokid \
          -w /go/src/enokid \
          $(GORELEASER_IMAGE) \
          release \
          --timeout=90m \
          --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install osxcross
        run: |
          sudo apt-get update
          sudo apt-get install -y clang llvm build-essential
          git clone https://github.com/tpoechtrager/osxcross.git
          cd osxcross
          wget -O tarballs/MacOSX11.3.sdk.tar.xz https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX11.3.sdk.tar.xz
          UNATTENDED=yes ./build.sh
          echo "Check osxcross"
          ls ./target/bin
          # which oa64-clang
          # which o64-clang
          export PATH=$PATH:$(pwd)/target/bin

      - name: Debug osxcross
        run: |
          echo $PATH
          which o64-clang
          o64-clang --version

      # - name: Build
      #   uses: goreleaser/goreleaser-action@v6
      #   with:
      #     version: "~> v2"
      #     args: build --skip validate --snapshot

      # - name: Release
      #   uses: goreleaser/goreleaser-action@v6
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     version: "~> v2"
      #     args: release --skip validate --clean
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}